# Generated by Django 4.2.6 on 2023-10-23 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofiles", "0005_profile_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="stars",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
