# Generated by Django 4.2.6 on 2023-10-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_picture_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.picture",
            ),
        ),
    ]
