# Generated by Django 4.2.6 on 2023-10-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_product_image_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(blank=True, to="base.picture"),
        ),
    ]
