# Generated by Django 4.2.6 on 2023-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=250)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price_packages",
            field=models.ManyToManyField(to="base.pricepackage"),
        ),
    ]
